merge to master PR
ansaryergesh/enumerable_methods pull request #1
Opened 2019-08-15 04:18 UTC by ansaryergesh

2019-08-15 04:57 UTC, bellom requested changes
Hi Team,
Well done guys, kindly be aware that you are to use `Git Flow` but instead you used `Github`, make sure to use 'Git Flow' in the next project - `OOP`
Short Explanation Hint: 
`GitHub Flow`: Pull Requests is raise from feature branches to the master.
`Git Flow`: Pull Requests is raise from feature branches to the development.
**Two things to do to;**
1. Add linter's check and fix all errors if need too, checkout this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
![image](https://user-images.githubusercontent.com/31897434/63073279-0e393680-bf20-11e9-9c84-f142caf1e675.png)
If you are not having this check on your Github page, kindly visit :point_right:[ linter set up](https://github.com/microverseinc/linters-config/blob/master/ruby/.stickler.yml)
2. You need to include space around operators and indentation with two spaces should be applied.

_Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you_

2019-08-15 04:57 UTC, bellom commented on enumerable_method.rb
> +      i=0
Make sure that code is clean: indentation with two spaces, line lengths, spaces around operators - first section of [this link](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide).

2019-08-15 04:57 UTC, bellom commented on enumerable_method.rb
> +       i+=1
Make sure that code is clean: indentation with two spaces, line lengths, spaces around operators - first section of [this link](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide).

2019-08-15 04:57 UTC, bellom commented on enumerable_method.rb
> +      i=0
Make sure that code is clean: indentation with two spaces, line lengths, spaces around operators - first section of [this link](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide).

2019-08-15 04:57 UTC, bellom commented on enumerable_method.rb
> +        i+=1
Make sure that code is clean: indentation with two spaces, line lengths, spaces around operators - first section of [this link](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide).

2019-08-15 04:57 UTC, bellom commented on enumerable_method.rb
> +        val=yield(val,i)
Make sure that code is clean: indentation with two spaces, line lengths, spaces around operators - first section of [this link](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide).

2019-08-16 21:47 UTC, AdnanAfsari requested changes
Hello @ansaryergesh ✋ 

Nice work @ansaryergesh but you have to fix those linter errors to get 👍 .we can not approve project with linter errors because it looks unprofessional.

Please submit for anther review after making those changes
Happy Coding

2019-08-17 11:19 UTC, bellom approved these changes
Hi Team, 
**Make sure to use 'Git Flow' in the next project - `OOP`**
Short Explanation Hint: 
`GitHub Flow`: Pull Requests is raise from feature branches to the master.
`Git Flow`: Pull Requests is raise from feature branches to the development.

#### Congratulation :+1: 
Go head and merge !

2019-08-17 14:54 UTC, merged